### ISSUE TITLE
mods.Terrafirmacraft.ItemHeat.removeRecipe(<Inputstack>); does not work with crucible

### ISSUE THREAD

**Issue by wormzjl** [JAWolfe04/TFC-Tweaker#3]
The removed items cannot be heated in firepit and forge, but they can be smelted in the crucible without and heat provided

**Comment by wormzjl** [comment]
https://github.com/Shurgent/TFCTech/issues/16

**Comment by StrayWolfe** [comment]
Unfortunately, this is due to the crucible working in a way that I cannot alter as opposed to the fire and forge. I've spent several hours in the past trying to find a way to overcome the crucible but there is little I can do short of replacing the crucible. Thank you for your report.
